Add user service
kvtim/CryptoExchangeApi pull request #4
Opened 2023-03-31 14:47 UTC by kvtim

Create user service (Authentication, authorization, CRUD, change password)

2023-04-04 18:59 UTC, Vlad1slav-Hmeln1tsk1j requested changes

2023-04-04 18:59 UTC, Vlad1slav-Hmeln1tsk1j commented on CryptoExchange/Microservices/CurrencyManagement/CurrencyManagement.Api/Controllers/CurrenciesController.cs
> +            return Ok(_mapper.Map<IEnumerable<CurrencyWithDimensionDto>>(currencies));
If currencies will be null that's anyway will be ok?

2023-04-04 18:59 UTC, Vlad1slav-Hmeln1tsk1j commented on CryptoExchange/Microservices/CurrencyManagement/CurrencyManagement.Api/Controllers/CurrenciesController.cs
> +            return Ok(_mapper.Map<CurrencyDto>(currencyResult));
If something breaks, will everything be Ok?

2023-04-04 18:59 UTC, Vlad1slav-Hmeln1tsk1j commented on CryptoExchange/Microservices/CurrencyManagement/CurrencyManagement.Api/Controllers/CurrenciesController.cs
>              return Ok(updateCurrencyDto);
If something goes wrong, everything will still be OK?

2023-04-04 18:59 UTC, Vlad1slav-Hmeln1tsk1j commented on CryptoExchange/Microservices/CurrencyManagement/CurrencyManagement.Api/Controllers/CurrenciesController.cs
> +            return Ok(_mapper.Map<CurrencyDto>(currency));
If something goes wrong, everything will still be OK?

2023-04-04 18:59 UTC, Vlad1slav-Hmeln1tsk1j commented on CryptoExchange/Microservices/CurrencyManagement/CurrencyManagement.Api/Controllers/CurrenciesController.cs
> +            return Ok(_mapper.Map<CurrencyDto>(currency));
If something goes wrong, everything will still be OK?

2023-04-04 18:59 UTC, Vlad1slav-Hmeln1tsk1j commented on CryptoExchange/Microservices/UserManagement/UserManagement.Api/UserManagement.Api/Controllers/UsersController.cs
> +            if (token == null) return BadRequest("User already exists");
I don't think it's worth using an if loop without a body

2023-04-04 18:59 UTC, Vlad1slav-Hmeln1tsk1j commented on CryptoExchange/Microservices/UserManagement/UserManagement.Api/UserManagement.Api/Controllers/UsersController.cs
> +            return Ok(_mapper.Map<IEnumerable<UserDto>>(users));
If users will be null that's anyway will be ok?

2023-04-04 18:59 UTC, Vlad1slav-Hmeln1tsk1j commented on CryptoExchange/Microservices/UserManagement/UserManagement.Api/UserManagement.Api/Controllers/UsersController.cs
> +        }
too dirty controller

2023-04-04 18:59 UTC, Vlad1slav-Hmeln1tsk1j commented on CryptoExchange/Microservices/UserManagement/UserManagement.Api/UserManagement.Api/Program.cs
> +});
I think you need to use extension methods

2023-04-07 17:25 UTC, kvtim commented
Completed exception handling by custom ActionResult

2023-04-10 11:46 UTC, kvtim commented
Add validation

2023-04-11 11:42 UTC, merged